name: Deploy

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      - name: Create .env file
        run: echo "SLACK_WEBHOOK_NEWS_DRONE_JP_CH_URL=${{ secrets.SLACK_WEBHOOK_NEWS_DRONE_JP_CH_URL }}" > .env
