name: Run News Bot

on:
  workflow_call:
    inputs:
      bot_type:
        description: 'Bot type to run'
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  run-bot:
    name: Run News Bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Update dependencies
        run: |
          go mod tidy
          go mod download
          go mod verify

      - name: Run News Bot
        env:
          SLACK_WEBHOOK_NEWS_DRONE_JP_CH_URL: ${{ inputs.bot_type == 'drone' && secrets.SLACK_WEBHOOK_URL || '' }}
          SLACK_WEBHOOK_ECONOMIC_TIMES_URL: ${{ inputs.bot_type == 'economictimes' && secrets.SLACK_WEBHOOK_URL || '' }}
        run: go run cmd/newsbot/${{ inputs.bot_type }}/main.go
