name: Scheduled News Bots

on:
  schedule:
    - cron: '0 4 * * *'  # 毎日13時（JST）に実行（UTC 4:00）

jobs:
  deploy-drone:
    uses: ./.github/workflows/run-bot.yml
    with:
      bot_type: drone
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_NEWS_DRONE_JP_CH_URL }}

  deploy-economictimes:
    uses: ./.github/workflows/run-bot.yml
    with:
      bot_type: economictimes
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_ECONOMIC_TIMES_URL }} 
